services:
  tplink-api:
    container_name: tplink-api
    build: .
    ports:
      - "5000:5000"
    environment:
      TP_LINK_IP: 192.168.1.1
      TP_LINK_USERNAME: admin
      TP_LINK_PASSWORD: admin

